### ISSUE TITLE
psycopg.errors.UndefinedTable: relation "journal" does not exist

### ISSUE THREAD

**Issue by vjFaLk** [agritheory/mqtt-pg-logger#4]
Using `timescaledb-latest-pg16` docker image. When PG Logger gets a message on a topic, when trying to insert it into the DB, it throws this error. 

```
mqtt-pg-logger-mqtt-pg-logger-1  | 2024-09-25 11:51:32,499 [   ERROR] src.proxy_store: relation "journal" does not exist
mqtt-pg-logger-mqtt-pg-logger-1  | Traceback (most recent call last):
mqtt-pg-logger-mqtt-pg-logger-1  |   File "/mqtt-pg-logger/src/proxy_store.py", line 94, in run
mqtt-pg-logger-mqtt-pg-logger-1  |     if self._store_messages():
mqtt-pg-logger-mqtt-pg-logger-1  |   File "/mqtt-pg-logger/src/proxy_store.py", line 161, in _store_messages
mqtt-pg-logger-mqtt-pg-logger-1  |     self._message_store.store(messages)
mqtt-pg-logger-mqtt-pg-logger-1  |   File "/mqtt-pg-logger/src/message_store.py", line 65, in store
mqtt-pg-logger-mqtt-pg-logger-1  |     with cursor.copy(copy_statement) as copy:
mqtt-pg-logger-mqtt-pg-logger-1  |   File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
mqtt-pg-logger-mqtt-pg-logger-1  |     return next(self.gen)
mqtt-pg-logger-mqtt-pg-logger-1  |   File "/usr/local/lib/python3.7/site-packages/psycopg/cursor.py", line 908, in copy
mqtt-pg-logger-mqtt-pg-logger-1  |     raise ex.with_traceback(None)
mqtt-pg-logger-mqtt-pg-logger-1  | psycopg.errors.UndefinedTable: relation "journal" does not exist
```

**Comment by agritheory** [comment]
I think I have removed references and the ability to specify the table ("journal"), I think you want to use `pgqueuer` instead
